apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vue-app2
  template:
    metadata:
      labels:
        app: vue-app2
    spec:
      containers:
        - name: vue-app2
          image: libracoder/vue-app2
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: vue-app2
spec:
  selector:
    app: vue-app2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
